services:
  php:
    image: ghcr.io/open-telemetry/opentelemetry-php/opentelemetry-php-base:${PHP_VERSION:-8.1}
    volumes:
    - ./:/usr/src/myapp
    user: "${PHP_USER}:root"
    env_file:
      - .env
  zipkin:
    image: openzipkin/zipkin-slim@sha256:d951994017185bce1c859b62e13adf640e26c37e08b90ca2e4de2669dc1aad87
    ports:
    - 9411:9411
  jaeger:
    image: jaegertracing/all-in-one@sha256:ab6f1a1f0fb49ea08bcd19f6b84f6081d0d44b364b6de148e1798eb5816bacac
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9412
    ports:
    - 9412:9412
    - 16686:16686
  collector:
    image: otel/opentelemetry-collector-contrib@sha256:213886eb6407af91b87fa47551c3632be1a6419ff3a5114ef1e6fc364628496f
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./files/collector/otel-collector-config.yml:/etc/otel-collector-config.yml
