services:
  phpdoc:
    image: phpdoc/phpdoc:3@sha256:2b36e4f74937e40246d54ed12dfa4f988f21ed8d19e46f426ac3dc32eac2ff1d
    volumes:
      - ./:/data
  preview:
    image: nginx:alpine@sha256:b3c656d55d7ad751196f21b7fd2e8d4da9cb430e32f646adcf92441b72f82b14
    ports:
      - 8080:80
    volumes:
      - ./docs/build:/usr/share/nginx/html