services:
  phpdoc:
    image: phpdoc/phpdoc:3@sha256:34883e361bd0ff8c6ead79d508575b37f62e5ba11f8445c8db979416fa5bf664
    volumes:
      - ./:/data
  preview:
    image: nginx:alpine@sha256:b3c656d55d7ad751196f21b7fd2e8d4da9cb430e32f646adcf92441b72f82b14
    ports:
      - 8080:80
    volumes:
      - ./docs/build:/usr/share/nginx/html